export type CurrencyOption = {
  code: string;
  label: string;
  name: string;
  symbol: string;
};

export type LocaleOption = {
  code: string;
  label: string;
  name: string;
};

export const WORLD_CURRENCIES: CurrencyOption[] = [
  { code: "INR", name: "Indian Rupee", symbol: "₹", label: "INR — Indian Rupee (₹)" },
  { code: "USD", name: "US Dollar", symbol: "$", label: "USD — US Dollar ($)" },
  { code: "EUR", name: "Euro", symbol: "€", label: "EUR — Euro (€)" },
  { code: "GBP", name: "British Pound", symbol: "£", label: "GBP — British Pound (£)" },
  { code: "AED", name: "UAE Dirham", symbol: "د.إ", label: "AED — UAE Dirham (د.إ)" },
  { code: "SAR", name: "Saudi Riyal", symbol: "ر.س", label: "SAR — Saudi Riyal (ر.س)" },
  { code: "QAR", name: "Qatari Riyal", symbol: "ر.ق", label: "QAR — Qatari Riyal (ر.ق)" },
  { code: "KWD", name: "Kuwaiti Dinar", symbol: "د.ك", label: "KWD — Kuwaiti Dinar (د.ك)" },
  { code: "BHD", name: "Bahraini Dinar", symbol: ".د.ب", label: "BHD — Bahraini Dinar (.د.ب)" },
  { code: "OMR", name: "Omani Rial", symbol: "ر.ع.", label: "OMR — Omani Rial (ر.ع.)" },
  { code: "CAD", name: "Canadian Dollar", symbol: "$", label: "CAD — Canadian Dollar ($)" },
  { code: "AUD", name: "Australian Dollar", symbol: "$", label: "AUD — Australian Dollar ($)" },
  { code: "SGD", name: "Singapore Dollar", symbol: "$", label: "SGD — Singapore Dollar ($)" },
  { code: "NZD", name: "New Zealand Dollar", symbol: "$", label: "NZD — New Zealand Dollar ($)" },
  { code: "JPY", name: "Japanese Yen", symbol: "¥", label: "JPY — Japanese Yen (¥)" },
  { code: "CNY", name: "Chinese Yuan", symbol: "¥", label: "CNY — Chinese Yuan (¥)" },
  { code: "HKD", name: "Hong Kong Dollar", symbol: "$", label: "HKD — Hong Kong Dollar ($)" },
  { code: "CHF", name: "Swiss Franc", symbol: "CHF", label: "CHF — Swiss Franc (CHF)" },
  { code: "ZAR", name: "South African Rand", symbol: "R", label: "ZAR — South African Rand (R)" },
  { code: "BRL", name: "Brazilian Real", symbol: "R$", label: "BRL — Brazilian Real (R$)" },
  { code: "MXN", name: "Mexican Peso", symbol: "$", label: "MXN — Mexican Peso ($)" },
  { code: "MYR", name: "Malaysian Ringgit", symbol: "RM", label: "MYR — Malaysian Ringgit (RM)" },
  { code: "THB", name: "Thai Baht", symbol: "฿", label: "THB — Thai Baht (฿)" },
  { code: "IDR", name: "Indonesian Rupiah", symbol: "Rp", label: "IDR — Indonesian Rupiah (Rp)" },
  { code: "PHP", name: "Philippine Peso", symbol: "₱", label: "PHP — Philippine Peso (₱)" },
  { code: "KRW", name: "South Korean Won", symbol: "₩", label: "KRW — South Korean Won (₩)" },
  { code: "VND", name: "Vietnamese Dong", symbol: "₫", label: "VND — Vietnamese Dong (₫)" },
  { code: "RUB", name: "Russian Ruble", symbol: "₽", label: "RUB — Russian Ruble (₽)" },
  { code: "TRY", name: "Turkish Lira", symbol: "₺", label: "TRY — Turkish Lira (₺)" },
  { code: "SEK", name: "Swedish Krona", symbol: "kr", label: "SEK — Swedish Krona (kr)" },
  { code: "NOK", name: "Norwegian Krone", symbol: "kr", label: "NOK — Norwegian Krone (kr)" },
  { code: "DKK", name: "Danish Krone", symbol: "kr", label: "DKK — Danish Krone (kr)" },
  { code: "PLN", name: "Polish Zloty", symbol: "zł", label: "PLN — Polish Zloty (zł)" },
  { code: "EGP", name: "Egyptian Pound", symbol: "E£", label: "EGP — Egyptian Pound (E£)" },
  { code: "NGN", name: "Nigerian Naira", symbol: "₦", label: "NGN — Nigerian Naira (₦)" },
  { code: "KES", name: "Kenyan Shilling", symbol: "KSh", label: "KES — Kenyan Shilling (KSh)" },
  { code: "PKR", name: "Pakistani Rupee", symbol: "Rs", label: "PKR — Pakistani Rupee (Rs)" },
  { code: "BDT", name: "Bangladeshi Taka", symbol: "৳", label: "BDT — Bangladeshi Taka (৳)" },
  { code: "LKR", name: "Sri Lankan Rupee", symbol: "Rs", label: "LKR — Sri Lankan Rupee (Rs)" },
  { code: "NPR", name: "Nepalese Rupee", symbol: "Rs", label: "NPR — Nepalese Rupee (Rs)" },
  { code: "ILS", name: "Israeli New Shekel", symbol: "₪", label: "ILS — Israeli New Shekel (₪)" },
  { code: "CLP", name: "Chilean Peso", symbol: "$", label: "CLP — Chilean Peso ($)" },
  { code: "COP", name: "Colombian Peso", symbol: "$", label: "COP — Colombian Peso ($)" },
  { code: "PEN", name: "Peruvian Sol", symbol: "S/", label: "PEN — Peruvian Sol (S/)" },
  { code: "ARS", name: "Argentine Peso", symbol: "$", label: "ARS — Argentine Peso ($)" },
  { code: "CZK", name: "Czech Koruna", symbol: "Kč", label: "CZK — Czech Koruna (Kč)" },
  { code: "HUF", name: "Hungarian Forint", symbol: "Ft", label: "HUF — Hungarian Forint (Ft)" },
  { code: "RON", name: "Romanian Leu", symbol: "lei", label: "RON — Romanian Leu (lei)" },
  { code: "TWD", name: "New Taiwan Dollar", symbol: "NT$", label: "TWD — New Taiwan Dollar (NT$)" },
];

export const WORLD_LOCALES: LocaleOption[] = [
  { code: "en-IN", name: "English (India)", label: "English (India)" },
  { code: "hi-IN", name: "Hindi", label: "Hindi — हिंदी" },
  { code: "en-US", name: "English (US)", label: "English (US)" },
  { code: "en-GB", name: "English (UK)", label: "English (UK)" },
  { code: "en-CA", name: "English (Canada)", label: "English (Canada)" },
  { code: "en-AU", name: "English (Australia)", label: "English (Australia)" },
  { code: "ar-AE", name: "Arabic (UAE)", label: "Arabic (UAE) — العربية" },
  { code: "ar-SA", name: "Arabic (Saudi Arabia)", label: "Arabic (Saudi Arabia) — العربية" },
  { code: "es-ES", name: "Spanish", label: "Spanish — Español" },
  { code: "fr-FR", name: "French", label: "French — Français" },
  { code: "de-DE", name: "German", label: "German — Deutsch" },
  { code: "pt-BR", name: "Portuguese (Brazil)", label: "Portuguese (Brazil) — Português" },
  { code: "ja-JP", name: "Japanese", label: "Japanese — 日本語" },
  { code: "zh-CN", name: "Chinese (Simplified)", label: "Chinese (Simplified) — 中文" },
  { code: "ru-RU", name: "Russian", label: "Russian — Русский" },
  { code: "it-IT", name: "Italian", label: "Italian — Italiano" },
  { code: "ko-KR", name: "Korean", label: "Korean — 한국어" },
  { code: "nl-NL", name: "Dutch", label: "Dutch — Nederlands" },
  { code: "tr-TR", name: "Turkish", label: "Turkish — Türkçe" },
  { code: "vi-VN", name: "Vietnamese", label: "Vietnamese — Tiếng Việt" },
  { code: "th-TH", name: "Thai", label: "Thai — ไทย" },
  { code: "id-ID", name: "Indonesian", label: "Indonesian — Bahasa Indonesia" },
  { code: "ms-MY", name: "Malay", label: "Malay — Bahasa Melayu" },
  { code: "bn-IN", name: "Bengali", label: "Bengali — বাংলা" },
  { code: "ta-IN", name: "Tamil", label: "Tamil — தமிழ்" },
  { code: "te-IN", name: "Telugu", label: "Telugu — తెలుగు" },
  { code: "mr-IN", name: "Marathi", label: "Marathi — मराठी" },
  { code: "gu-IN", name: "Gujarati", label: "Gujarati — ગુજરાતી" },
  { code: "kn-IN", name: "Kannada", label: "Kannada — ಕನ್ನಡ" },
  { code: "ml-IN", name: "Malayalam", label: "Malayalam — മലയാളം" },
  { code: "pa-IN", name: "Punjabi", label: "Punjabi — ਪੰਜਾਬੀ" },
  { code: "ur-PK", name: "Urdu", label: "Urdu — اردو" },
];
